version: '3.9'
services:
    backend:
        image: backend:1.0
        build:
            context: ./
            dockerfile: ./backend/Dockerfile
        ports:
            - ${API_PORT}:${API_PORT}
        restart: unless-stopped
    mysqldb:
        image: mysql:5.7
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQLDB_DATABASE
        ports:
            - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
        volumes:
            - db:/var/lib/mysql

volumes:
    db:
